name: Nightly Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Sign

    runs-on: macos-11.0

    steps:
      - name: Checkout Hammerspoon Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout Hammerspoon Secrets
        uses: actions/checkout@v2
        with:
          repository: Hammerspoon/ci-secrets
          path: ./ci-secrets
      - name: Prepare build environment
        run: ./scripts/github-ci-pre.sh
      - name: Decrypt Secrets
        env:
          REPO_GPG_PASSPHRASE: ${{ secrets.REPO_GPG_PASSPHRASE }}
        run: ./ci-secrets/crypto.sh decrypt
      - name: Import signing key
        run: /usr/bin/security import ./ci-secrets/Cleartext/Hammerspoon_Nightly-developerID_application.cer
      - name: Prepare secure tokens
        run: |
          /bin/cp ./ci-secrets/Cleartext/token* ../
          ls -l ..
      - name: Remove Secrets checkout
        run: /bin/rm -rf ./ci-secrets
      - name: Get version number
        id: version
        run: |
          echo ::set-output name=NIGHTLY_VERSION::$(git describe)
      - name: Build
        run: ./scripts/release.sh --nightly
      - name: Upload build log on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: build/Release-build.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
              ../archive/${{ steps.version.outputs.NIGHTLY_VERSION }}/Hammerspoon-${{ steps.version.outputs.NIGHTLY_VERSION }}.zip
              ../archive/${{ steps.version.outputs.NIGHTLY_VERSION }}/Hammerspoon-dSYM-${{ steps.version.outputs.NIGHTLY_VERSION }}.zip
              ../archive/${{ steps.version.outputs.NIGHTLY_VERSION }}/Hammerspoon-docs-${{ steps.version.outputs.NIGHTLY_VERSION }}.zip
              ../archive/${{ steps.version.outputs.NIGHTLY_VERSION }}/dSYM_UUID.txt
              ../archive/${{ steps.version.outputs.NIGHTLY_VERSION }}/release-build.log
              ../archive/${{ steps.version.outputs.NIGHTLY_VERSION }}/notarization-upload.log
      - name: IRC notification
        uses: Gottox/irc-message-action@v1.3.0
        with:
          channel: '#hammerspoon'
          nickname: 'HS_CI_Nightly'
          message: |
            New nightly build: ${{ steps.version.outputs.NIGHTLY_VERSION }}
