name: 'Close stale Issues/PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue needs more information. Please see our request above.'
          close-issue-message: 'No information was received, closing this Issue for now.'
          stale-issue-label: 'stale'
          days-before-issue-stale: 30
          days-before-issue-close: 30
          only-labels: 'needs-response'
          days-before-pr-stale: -1
          days-before-pr-close: -1
